### ISSUE TITLE
연결 에러

### ISSUE THREAD

**Issue by jeonghoonkang** [zerover0/projects#1]
http://49.254.13.34:8000/ 연결이 거부됩니다.

**Comment by zerover0** [comment]
Django 서버는 일반 웹서비스랑 다르게 프로젝트 단위로 연결포트를 지정해 실행할 수 있는데, 현재 앱코드를 개발 중인 상태라서
시험할 때만 띄우고 평소에는 종료해두고 있습니다.
다음 주에 앱 코드가 안정되면 프로젝트 서버를 계속 띄워놓겠습니다.

김상한
2016. 4. 29. 오후 1:06에 "TinyOS Lover (3PO_Kang)" notifications@github.com님이
작성:
